//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoManager.Service.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumPhoto
    {
        public int Id { get; set; }
        public int AlbumId { get; set; }
        public int PhotoId { get; set; }
        public Nullable<bool> IsTitlePhoto { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Photo Photo { get; set; }
    }
}
